server:
  port: 8080

spring:
  application:
    name: API_GATEWAY

  cloud:
    gateway:
      routes:
        - id: gloQuora
          uri:
            lb://gloQuora
          predicates:
            - Path=/GloQuora/**


        - id: User
          uri:
            lb://User
          predicates:
            - Path=/User/**


        - id: adminapp
          uri:
            lb://adminapp
          predicates:
            - Path=/adminapp/**
